import memberWorker from "./worker-member-v2";
import { getMember } from "./lib/member";
import { validateMemberBooking } from "./lib/member-booking-validation";

type Env = { ENVIRONMENT?: string; NOTION_TOKEN: string; NOTION_PARENT_DATA_SOURCE_ID: string; NOTION_STUDENT_DATA_SOURCE_ID: string; NOTION_OS_SESSION_DATA_SOURCE_ID: string; NOTION_OS_SESSION_DATABASE_ID?: string; NOTION_OS_BOOKING_DATA_SOURCE_ID: string; NOTION_OS_PASS_DATA_SOURCE_ID: string; NOTION_RUNNING_CLASS_DATA_SOURCE_ID: string; NOTION_PATH_PROGRAM_DATA_SOURCE_ID: string; };
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{"Content-Type":"application/json","Cache-Control":"no-store, no-cache, must-revalidate","Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"Content-Type","Access-Control-Allow-Methods":"GET, POST, OPTIONS"}});
const notionHeaders=(env:Env,version="2026-03-11")=>({Authorization:`Bearer ${env.NOTION_TOKEN}`,"Content-Type":"application/json","Notion-Version":version});
const isProduction=(env:Env)=>(env.ENVIRONMENT||"production")==="production";
const text=(p:any)=>p?.title?.[0]?.plain_text||p?.rich_text?.[0]?.plain_text||p?.select?.name||p?.status?.name||"";
const date=(p:any)=>p?.date?.start||null;
const number=(p:any)=>typeof p?.number==="number"?p.number:typeof p?.formula?.number==="number"?p.formula.number:typeof p?.rollup?.number==="number"?p.rollup.number:null;
const files=(p:any)=>p?.files?.map((f:any)=>f.file?.url||f.external?.url).filter(Boolean)||[];
const relationIds=(p:any):string[]=>{if(Array.isArray(p?.relation))return p.relation.map((r:any)=>r.id).filter(Boolean);if(Array.isArray(p?.rollup?.array))return p.rollup.array.flatMap((item:any)=>item?.relation||[]).map((r:any)=>r.id).filter(Boolean);return[];};
const select=(p:any)=>p?.select?.name||p?.status?.name||null;
const publicPath=(value:string|null)=>{const v=(value||"").trim().toLowerCase().replace(/\s+/g," ");if(v==="pianohouse"||v.startsWith("piano"))return "Piano";if(v==="architect"||v.startsWith("architect")||v.startsWith("mỹ thuật")||v.startsWith("my thuat"))return "Mỹ thuật";if(v==="little piner"||v.startsWith("little piner"))return "Little Piner";return null;};
async function notionQuery(env:Env,dataSourceId:string,filter?:unknown){const response=await fetch(`https://api.notion.com/v1/data_sources/${dataSourceId}/query`,{method:"POST",headers:notionHeaders(env),body:JSON.stringify(filter?{filter}:{})});if(response.ok)return response;if(dataSourceId===env.NOTION_OS_SESSION_DATA_SOURCE_ID&&env.NOTION_OS_SESSION_DATABASE_ID)return fetch(`https://api.notion.com/v1/databases/${env.NOTION_OS_SESSION_DATABASE_ID}/query`,{method:"POST",headers:notionHeaders(env,"2022-06-28"),body:JSON.stringify(filter?{filter}:{})});return response;}
async function getLightSessions(env:Env,params:URLSearchParams){const type=params.get("type");const filter=type?{property:"Type",select:{equals:type}}:undefined;const [sessionsResponse,programsResponse]=await Promise.all([notionQuery(env,env.NOTION_OS_SESSION_DATA_SOURCE_ID,filter),notionQuery(env,env.NOTION_PATH_PROGRAM_DATA_SOURCE_ID)]);if(!sessionsResponse.ok)return json({error:"Could not load OS sessions.",notionStatus:sessionsResponse.status},502);const sessionsData=await sessionsResponse.json() as any;const programMap=new Map<string,string>();if(programsResponse.ok){const programs=await programsResponse.json() as any;for(const page of programs.results||[]){const path=publicPath(select(page.properties?.Path));if(path)programMap.set(page.id,path);}}
const items=(sessionsData.results||[]).filter((page:any)=>!isProduction(env)||page.properties?.["Mock Data"]?.checkbox!==true).map((page:any)=>{const paths=relationIds(page.properties?.["Path Program"]).map((id:string)=>programMap.get(id)).filter(Boolean);const confirmedCount=number(page.properties?.["Confirmed Count"]);const capacity=number(page.properties?.Capacity);const availableSeats=number(page.properties?.["Available Seats"]);return{id:page.id,topic:text(page.properties?.Topic)||"Untitled session",type:text(page.properties?.Type),path:paths[0]||null,date:date(page.properties?.Date),availableSeats:availableSeats??(capacity!==null&&confirmedCount!==null?Math.max(0,capacity-confirmedCount):null),capacity,confirmedCount,runningClassIds:relationIds(page.properties?.["Running Class"]),cover:files(page.properties?.Cover)[0]||null,avatar:files(page.properties?.Avatar)[0]||null};}).sort((a:any,b:any)=>(a.date||"9999").localeCompare(b.date||"9999"));const requestedPath=params.get("path");return json({sessions:requestedPath?items.filter((item:any)=>item.path===requestedPath):items});}
async function notionPage(env:Env,pageId:string){const response=await fetch(`https://api.notion.com/v1/pages/${pageId}`,{headers:notionHeaders(env)});if(!response.ok)return null;return await response.json() as any;}
async function rejectMockSessionInProduction(env:Env,sessionId:string|null){if(!isProduction(env)||!sessionId)return null;const page=await notionPage(env,sessionId);if(!page)return null;if(page.properties?.["Mock Data"]?.checkbox===true)return json({error:"This session is not available in production."},404);return null;}
const handler={async fetch(request:Request,env:Env){if(request.method==="OPTIONS")return memberWorker.fetch(request,env as any);const url=new URL(request.url);if(request.method==="POST"&&url.pathname==="/api/member"){let body:any;try{body=await request.json();}catch{return json({error:"Invalid request."},400);}const result=await getMember(env,typeof body?.phone==="string"?body.phone:"");return result.ok?json(result):json(result,result.status);}if(request.method==="POST"&&url.pathname==="/api/member/book/validate"){let body:any;try{body=await request.json();}catch{return json({error:"Invalid request."},400);}const result=await validateMemberBooking(env,body);return result.ok?json(result):json(result,result.status);}if(url.pathname==="/api/os-sessions"&&request.method==="GET"){return getLightSessions(env,url.searchParams);}if(isProduction(env)&&request.method==="POST"&&(url.pathname==="/api/member/book"||url.pathname==="/api/open-studio/book")){let body:any=null;try{body=await request.clone().json();}catch{}const sessionId=typeof body?.sessionId==="string"?body.sessionId:typeof body?.osSessionId==="string"?body.osSessionId:typeof body?.session==="string"?body.session:null;const blocked=await rejectMockSessionInProduction(env,sessionId);if(blocked)return blocked;}return memberWorker.fetch(request,env as any);}};
export default handler;
