import worker from "./worker";
import { getMember } from "./lib/member";

type Env={NOTION_TOKEN:string;NOTION_PARENT_DATA_SOURCE_ID:string;NOTION_STUDENT_DATA_SOURCE_ID:string;NOTION_OS_PASS_DATA_SOURCE_ID:string;NOTION_OS_BOOKING_DATA_SOURCE_ID:string;NOTION_OS_BOOKING_DATABASE_ID?:string;NOTION_OS_SESSION_DATA_SOURCE_ID:string;NOTION_OS_SESSION_DATABASE_ID?:string;NOTION_RUNNING_CLASS_DATA_SOURCE_ID:string;NOTION_PATH_PROGRAM_DATA_SOURCE_ID:string};
const corsHeaders={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"Content-Type","Access-Control-Allow-Methods":"GET, POST, OPTIONS"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{"Content-Type":"application/json",...corsHeaders}});
const headers=(env:Env,version="2026-03-11")=>({Authorization:`Bearer ${env.NOTION_TOKEN}`,"Content-Type":"application/json","Notion-Version":version});
const query=async(env:Env,id:string,filter?:unknown,sorts?:unknown[])=>{const body:any={...(filter?{filter}:{}),...(sorts?{sorts}:{})};const response=await fetch(`https://api.notion.com/v1/data_sources/${id}/query`,{method:"POST",headers:headers(env),body:JSON.stringify(body)});if(response.ok)return response;if(id===env.NOTION_OS_SESSION_DATA_SOURCE_ID&&env.NOTION_OS_SESSION_DATABASE_ID)return fetch(`https://api.notion.com/v1/databases/${env.NOTION_OS_SESSION_DATABASE_ID}/query`,{method:"POST",headers:headers(env,"2022-06-28"),body:JSON.stringify(body)});if(id===env.NOTION_OS_BOOKING_DATA_SOURCE_ID&&env.NOTION_OS_BOOKING_DATABASE_ID)return fetch(`https://api.notion.com/v1/databases/${env.NOTION_OS_BOOKING_DATABASE_ID}/query`,{method:"POST",headers:headers(env,"2022-06-28"),body:JSON.stringify(body)});return response;};
const createPage=(env:Env,id:string,properties:Record<string,unknown>)=>fetch("https://api.notion.com/v1/pages",{method:"POST",headers:headers(env),body:JSON.stringify({parent:{data_source_id:id},properties})});
const updatePage=(env:Env,id:string,properties:Record<string,unknown>)=>fetch(`https://api.notion.com/v1/pages/${id}`,{method:"PATCH",headers:headers(env),body:JSON.stringify({properties})});
const trashPage=(env:Env,id:string)=>fetch(`https://api.notion.com/v1/pages/${id}`,{method:"PATCH",headers:headers(env),body:JSON.stringify({in_trash:true})});
const text=(p:any)=>p?.title?.[0]?.plain_text||p?.rich_text?.[0]?.plain_text||p?.select?.name||"";
const date=(p:any)=>p?.date?.start||null;
const select=(p:any)=>p?.select?.name||null;
const relationIds=(p:any):string[]=>p?.relation?.map((r:any)=>r.id).filter(Boolean)||[];
const number=(p:any)=>typeof p?.number==="number"?p.number:typeof p?.formula?.number==="number"?p.formula.number:typeof p?.rollup?.number==="number"?p.rollup.number:null;
const localDate=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Ho_Chi_Minh",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
const cycleStart=()=>`${localDate().slice(0,7)}-01`;
const cycleEnd=(start:string)=>{const [y,m]=start.split("-").map(Number);return new Date(Date.UTC(y,m,0)).toISOString().slice(0,10)};
const passTypes=["Piano","Art","Little Piner","Bring-a-Friend"] as const;
const passRules:Record<(typeof passTypes)[number],{scope:"Open Studio + Premium"|"Any";path:string|null}>={Piano:{scope:"Open Studio + Premium",path:"Piano"},Art:{scope:"Open Studio + Premium",path:"Mỹ thuật"},"Little Piner":{scope:"Open Studio + Premium",path:"Little Piner"},"Bring-a-Friend":{scope:"Any",path:null}};
const membershipGrantFilter={or:[{property:"Grant Type",select:{equals:"Premium"}},{property:"Grant Type",select:{equals:"Welcome"}}]};

async function getStudentSubscription(env:Env,studentId:string){const studentResponse=await fetch(`https://api.notion.com/v1/pages/${studentId}`,{headers:headers(env)});if(!studentResponse.ok)return null;const student=await studentResponse.json() as any;const subscriptionId=relationIds(student.properties?.["Subscription Plan"])[0];if(!subscriptionId)return null;const response=await fetch(`https://api.notion.com/v1/pages/${subscriptionId}`,{headers:headers(env)});if(!response.ok)return null;const p=(await response.json() as any).properties||{};const start=date(p["Start Date"]),end=date(p["End Date"]),today=localDate();if(start&&start>today)return null;if(end&&end<today)return null;return {id:subscriptionId,startDate:start,endDate:end};}

async function getProgramContext(env:Env){const [classes,programs]=await Promise.all([query(env,env.NOTION_RUNNING_CLASS_DATA_SOURCE_ID),query(env,env.NOTION_PATH_PROGRAM_DATA_SOURCE_ID)]);if(!classes.ok||!programs.ok)return {paths:new Map<string,string>(),caps:new Map<string,number>()};const pData=await programs.json() as any,cData=await classes.json() as any;const paths=new Map<string,string>();for(const p of pData.results||[]){const v=(select(p.properties?.["Master Path"])||"").toLowerCase().trim();const path=v==="pianohouse"?"Piano":v==="architect"?"Mỹ thuật":v==="little piner"?"Little Piner":null;if(path)paths.set(p.id,path);}const caps=new Map<string,number>();const classPaths=new Map<string,string>();for(const p of cData.results||[]){const id=relationIds(p.properties?.["Path Program"])[0];if(id&&paths.has(id))classPaths.set(p.id,paths.get(id)!);const n=number(p.properties?.Capacity);if(n!==null)caps.set(p.id,n);}return {paths:classPaths,caps};}

async function getSession(env:Env,sessionId:string){const response=await fetch(`https://api.notion.com/v1/pages/${sessionId}`,{headers:headers(env)});if(!response.ok)return {ok:false as const,status:response.status===404?404:502,error:response.status===404?"Session not found.":"Could not load session."};const page=await response.json() as any,ctx=await getProgramContext(env),classes=relationIds(page.properties?.["Running Class"]);const paths=classes.map(id=>ctx.paths.get(id)).filter(Boolean) as string[];const capacities=classes.map(id=>ctx.caps.get(id)).filter((v):v is number=>typeof v==="number");const capacity=capacities.length?capacities.reduce((a,b)=>a+b,0):null;const bookings=await query(env,env.NOTION_OS_BOOKING_DATA_SOURCE_ID,{and:[{property:"OS Session",relation:{contains:sessionId}},{property:"Status",select:{equals:"Confirmed"}}]});if(!bookings.ok)return {ok:false as const,status:502,error:"Could not check session capacity."};const data=await bookings.json() as any;const confirmed=data.results?.length||0;return {ok:true as const,session:{id:sessionId,topic:text(page.properties?.Topic)||"Open Studio session",type:text(page.properties?.Type),path:paths[0]||null,date:date(page.properties?.Date),capacity,confirmedCount:confirmed,availableSeats:capacity===null?null:Math.max(0,capacity-confirmed)}};}

async function currentPasses(env:Env,studentId:string){const start=cycleStart();const response=await query(env,env.NOTION_OS_PASS_DATA_SOURCE_ID,{and:[{property:"Student",relation:{contains:studentId}},{property:"Cycle Start",date:{equals:start}},{property:"Status",select:{equals:"Available"}}]});if(!response.ok)return {ok:false as const,status:502,error:"Could not load current Open Studio passes.",notionStatus:response.status};const data=await response.json() as any;return {ok:true as const,results:data.results||[],cycleStart:start};}

async function dedupeCycle(env:Env,studentId:string,start:string){const response=await query(env,env.NOTION_OS_PASS_DATA_SOURCE_ID,{and:[{property:"Student",relation:{contains:studentId}},{property:"Cycle Start",date:{equals:start}},membershipGrantFilter]},{timestamp:"created_time",direction:"ascending"} as any[]);if(!response.ok)return;const data=await response.json() as any;const seen=new Set<string>();for(const page of data.results||[]){const type=select(page.properties?.["Pass Type"]);if(!type||!passTypes.includes(type as any))continue;if(seen.has(type))await trashPage(env,page.id);else seen.add(type);}}

async function ensurePremiumPasses(env:Env,studentId:string){const subscription=await getStudentSubscription(env,studentId);if(!subscription)return {ok:true as const,eligible:false,created:0,available:0};const start=cycleStart(),end=cycleEnd(start);const filter={and:[{property:"Student",relation:{contains:studentId}},{property:"Cycle Start",date:{equals:start}},membershipGrantFilter]};const existingResponse=await query(env,env.NOTION_OS_PASS_DATA_SOURCE_ID,filter);if(!existingResponse.ok)return {ok:false as const,status:502,error:"Could not check current Open Studio entitlement cycle.",notionStatus:existingResponse.status};const existing=await existingResponse.json() as any;const existingTypes=new Set((existing.results||[]).map((p:any)=>select(p.properties?.["Pass Type"])).filter(Boolean));const created:string[]=[];for(const type of passTypes){if(existingTypes.has(type))continue;const rule=passRules[type];const response=await createPage(env,env.NOTION_OS_PASS_DATA_SOURCE_ID,{Name:{title:[{text:{content:`${type} · ${start}`}}]},Student:{relation:[{id:studentId}]},"Pass Type":{select:{name:type}},Status:{select:{name:"Available"}},"Access Scope":{select:{name:rule.scope}},"Cycle Start":{date:{start}},"Valid Until":{date:{start:end}},"Grant Type":{select:{name:"Premium"}},"Mock Data":{checkbox:false}});if(!response.ok)return {ok:false as const,status:502,error:"Could not create Premium Open Studio pass.",notionStatus:response.status,created};const page=await response.json() as any;if(page.id)created.push(page.id);}await dedupeCycle(env,studentId,start);const refreshed=await currentPasses(env,studentId);return {ok:true as const,eligible:true,created:created.length,available:refreshed.ok?refreshed.results.length:0};}

async function createBooking(env:Env,phone:string,studentId:string,sessionId:string,passId:string){const member=await getMember(env,phone);if(!member.ok)return member;if(!member.member.students.some((s:any)=>s.id===studentId))return {ok:false as const,status:403,error:"This student does not belong to this member."};const entitlement=await ensurePremiumPasses(env,studentId);if(!entitlement.ok)return entitlement;const passes=await currentPasses(env,studentId);if(!passes.ok)return passes;const pass=passes.results.find((p:any)=>p.id===passId);if(!pass)return {ok:false as const,status:409,error:"This Open Studio pass is not available in the current cycle."};const validUntil=date(pass.properties?.["Valid Until"]);if(validUntil&&validUntil<localDate())return {ok:false as const,status:409,error:"This Open Studio pass has expired."};const sessionResult=await getSession(env,sessionId);if(!sessionResult.ok)return sessionResult;const session=sessionResult.session;if(session.type!=="Open Studio"&&session.type!=="Premium")return {ok:false as const,status:409,error:"This session is not bookable with an Open Studio pass."};if(session.availableSeats!==null&&session.availableSeats<=0)return {ok:false as const,status:409,error:"This session is sold out."};const passType=select(pass.properties?.["Pass Type"]);const path=passType==="Piano"?"Piano":passType==="Art"?"Mỹ thuật":passType==="Little Piner"?"Little Piner":null;if(passType!=="Bring-a-Friend"&&path!==session.path)return {ok:false as const,status:409,error:"This pass cannot access this session."};const duplicate=await query(env,env.NOTION_OS_BOOKING_DATA_SOURCE_ID,{and:[{property:"Student",relation:{contains:studentId}},{property:"OS Session",relation:{contains:sessionId}},{property:"Status",select:{equals:"Confirmed"}}]});if(!duplicate.ok)return {ok:false as const,status:502,error:"Could not check existing booking."};const duplicateData=await duplicate.json() as any;if((duplicateData.results?.length||0)>0)return {ok:false as const,status:409,error:"This student is already booked for this session."};const booking=await createPage(env,env.NOTION_OS_BOOKING_DATA_SOURCE_ID,{Name:{title:[{text:{content:`${session.topic} · ${studentId.slice(0,6)}`}}]},Student:{relation:[{id:studentId}]},"OS Session":{relation:[{id:sessionId}]},"OS Pass":{relation:[{id:passId}]},Status:{select:{name:"Confirmed"}}});if(!booking.ok)return {ok:false as const,status:502,error:"Could not create booking.",detail:(await booking.text()).slice(0,500)};const created=await booking.json() as any;if(!created.id)return {ok:false as const,status:502,error:"Booking created without an ID."};const consumed=await updatePage(env,passId,{Status:{select:{name:"Used"}}});if(!consumed.ok)return {ok:false as const,status:502,error:"Booking was created but pass could not be consumed.",bookingId:created.id};return {ok:true as const,bookingId:created.id,studentId,sessionId,passId,status:"Confirmed",sessionTopic:session.topic,sessionDate:session.date};}

const memberHandler={async fetch(request:Request,env:Env){const url=new URL(request.url);if(request.method==="OPTIONS")return new Response(null,{headers:corsHeaders});if(url.pathname==="/api/member"){if(request.method!=="POST")return json({error:"Method not allowed"},405);let body:any;try{body=await request.json()}catch{return json({error:"Invalid request."},400)}const phone=typeof body?.phone==="string"?body.phone.trim():"";if(!phone)return json({error:"phone is required."},400);const member=await getMember(env,phone);if(!member.ok)return json(member,member.status);const results=await Promise.all(member.member.students.map((s:any)=>ensurePremiumPasses(env,s.id)));const failed=results.find((r:any)=>!r.ok);if(failed)return json(failed,failed.status);const refreshed=await getMember(env,phone);return refreshed.ok?json(refreshed):json(refreshed,refreshed.status);}if(url.pathname==="/api/member/book"){if(request.method!=="POST")return json({error:"Method not allowed"},405);let body:any;try{body=await request.json()}catch{return json({error:"Invalid request."},400)}const phone=typeof body?.phone==="string"?body.phone.trim():"",studentId=typeof body?.studentId==="string"?body.studentId:"",sessionId=typeof body?.sessionId==="string"?body.sessionId:"",passId=typeof body?.passId==="string"?body.passId:"";if(!phone||!studentId||!sessionId||!passId)return json({error:"phone, studentId, sessionId and passId are required."},400);const result=await createBooking(env,phone,studentId,sessionId,passId);return result.ok?json(result):json(result,result.status);}if(url.pathname==="/api/member/activate")return json({ok:false,error:"Legacy activation flow disabled. Membership is determined by the student's Subscription."},410);return worker.fetch(request,env as any);}};
export default memberHandler;
