"use client";

import { useEffect, useMemo, useState } from "react";

type Session = { id:string; topic:string; type:string; path:string|null; date:string|null; availableSeats:number|null; capacity:number|null; confirmedCount:number|null; runningClassIds:string[]; cover:string|null; avatar:string|null };
const filters=["All","Piano","Mỹ thuật","Little Piner"];
const dayKey=(d:string|null)=>d?new Date(d).toISOString().slice(0,10):"unknown";
const dayLabel=(d:string)=>new Intl.DateTimeFormat("en-US",{weekday:"short"}).format(new Date(`${d}T12:00:00`));
const dateLabel=(d:string)=>new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric"}).format(new Date(`${d}T12:00:00`));

export default function SessionsPage(){
 const [sessions,setSessions]=useState<Session[]>([]); const [filter,setFilter]=useState("All"); const [selectedDay,setSelectedDay]=useState(""); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
 useEffect(()=>{fetch("/api/os-sessions").then(async r=>{const data=await r.json();if(!r.ok)throw new Error(data.error||"Could not load sessions.");return data}).then(data=>{const list=data.sessions||[];setSessions(list);const days=[...new Set(list.filter((s:Session)=>s.date).map((s:Session)=>dayKey(s.date)))];setSelectedDay(days[0]||"")}).catch(e=>setError(e.message||"Could not load sessions.")).finally(()=>setLoading(false))},[]);
 const filtered=useMemo(()=>filter==="All"?sessions:sessions.filter(s=>s.path===filter),[filter,sessions]);
 const days=useMemo(()=>[...new Set(filtered.filter(s=>s.date).map(s=>dayKey(s.date)))].sort(),[filtered]);
 useEffect(()=>{if(days.length&&!days.includes(selectedDay))setSelectedDay(days[0])},[days,selectedDay]);
 const visible=filtered.filter(s=>dayKey(s.date)===selectedDay);
 return <main style={{minHeight:"100vh",background:"#f4f0e7",color:"#171713"}}>
  <nav className="shell" style={{height:84,display:"flex",alignItems:"center",justifyContent:"space-between",borderBottom:"1px solid rgba(23,23,19,.16)"}}><a href="/" style={{fontWeight:700,fontSize:24,letterSpacing:"-.08em"}}>PINO<span style={{color:"#d65b42",marginLeft:3}}>•</span></a><a href="/open-studio" style={{fontSize:14,fontWeight:600}}>Get a pass →</a></nav>
  <section className="shell" style={{padding:"82px 0 42px"}}><p style={{fontSize:11,letterSpacing:".15em",fontWeight:700,color:"#69655d",marginBottom:18}}>PINO OPEN STUDIO</p><h1 style={{fontSize:"clamp(54px,7vw,96px)",lineHeight:.9,letterSpacing:"-.065em",maxWidth:850,margin:0}}>Find a session.<br/><em style={{fontFamily:"DM Serif Display,serif",fontWeight:400}}>Come make something.</em></h1><p style={{maxWidth:570,color:"#777269",fontSize:18,lineHeight:1.6,marginTop:28}}>Choose a day, find something interesting, and use an eligible pass when you are ready to join.</p></section>
  <section className="shell" style={{paddingBottom:100}}>
   <div className="filter-row" style={{display:"flex",gap:8,overflowX:"auto",paddingBottom:4,marginBottom:26}}>{filters.map(item=><button key={item} onClick={()=>setFilter(item)} style={{whiteSpace:"nowrap",border:filter===item?"1px solid #171713":"1px solid rgba(23,23,19,.16)",background:filter===item?"#171713":"transparent",color:filter===item?"#fff":"#171713",borderRadius:999,padding:"10px 16px",cursor:"pointer",fontSize:13,fontWeight:600}}>{item}</button>)}</div>
   {!loading&&!error&&days.length>0&&<div className="day-rail" style={{display:"flex",gap:8,overflowX:"auto",borderBottom:"1px solid rgba(23,23,19,.16)",marginBottom:38}}>{days.map(d=>{const count=filtered.filter(s=>dayKey(s.date)===d).length;return <button key={d} onClick={()=>setSelectedDay(d)} style={{minWidth:92,padding:"14px 12px 17px",border:0,borderBottom:selectedDay===d?"3px solid #171713":"3px solid transparent",background:"transparent",cursor:"pointer",textAlign:"left"}}><div style={{fontSize:11,letterSpacing:".08em",fontWeight:700}}>{dayLabel(d).toUpperCase()}</div><div style={{fontSize:25,letterSpacing:"-.04em",marginTop:3}}>{dateLabel(d)}</div><div style={{fontSize:11,color:"#777269",marginTop:5}}>{count} {count===1?"session":"sessions"}</div></button>})}</div>}
   {loading&&<p style={{color:"#777269"}}>Loading sessions…</p>}{error&&<div style={{padding:24,border:"1px solid rgba(166,59,42,.35)",color:"#a63b2a"}}>{error}</div>}{!loading&&!error&&days.length===0&&<div style={{padding:50,borderTop:"1px solid rgba(23,23,19,.16)",color:"#777269"}}>No sessions are available yet. Check back soon.</div>}
   {!loading&&!error&&days.length>0&&visible.length===0&&<div style={{padding:"45px 0",color:"#777269"}}>Nothing is open this day. Try another day →</div>}
   <div className="session-grid" style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:14}}>{visible.map(session=>{const isPremium=session.type==="Premium";const seats=session.availableSeats;const soldOut=seats!==null&&seats<=0;return <article key={session.id} style={{background:"#e8e0d1",border:"1px solid rgba(23,23,19,.12)",overflow:"hidden"}}><div style={{aspectRatio:"16/9",background:session.cover?`url(${session.cover}) center/cover`:"linear-gradient(135deg,#d9d0bd,#c6d5ba)",position:"relative"}}>{session.avatar&&<img src={session.avatar} alt="" style={{position:"absolute",width:64,height:64,objectFit:"cover",borderRadius:"50%",left:20,bottom:20,border:"3px solid #f4f0e7"}}/>}<span style={{position:"absolute",top:18,right:18,background:isPremium?"#e2ebc0":"#f4f0e7",padding:"8px 10px",fontSize:10,letterSpacing:".1em",fontWeight:700}}>{isPremium?"PREMIUM":"OPEN STUDIO"}</span></div><div style={{padding:26}}><p style={{margin:"0 0 10px",fontSize:11,letterSpacing:".12em",fontWeight:700,color:"#777269"}}>{session.path||"PINO SESSION"}</p><h2 style={{fontSize:32,lineHeight:1,letterSpacing:"-.05em",margin:"0 0 10px"}}>{session.topic}</h2><div style={{borderTop:"1px solid rgba(23,23,19,.14)",paddingTop:16,display:"flex",justifyContent:"space-between",gap:15,fontSize:12}}><span>{session.date?new Date(session.date).toLocaleTimeString("vi-VN",{hour:"2-digit",minute:"2-digit"}):"Time TBA"}</span><span>{seats===null?"Seats TBA":soldOut?"Sold out":`${seats} seats left`}</span></div><button disabled={soldOut} style={{width:"100%",marginTop:18,padding:"14px 18px",border:0,borderRadius:999,background:soldOut?"#c9c4b9":"#1d201a",color:"#fff",fontWeight:600,cursor:soldOut?"not-allowed":"pointer"}}>{soldOut?"Sold out":"Use my pass →"}</button></div></article>})}</div>
  </section><footer className="shell" style={{borderTop:"1px solid rgba(23,23,19,.16)",padding:"28px 0 40px",display:"flex",justifyContent:"space-between",color:"#777269",fontSize:12}}><span>PINO<span style={{color:"#d65b42"}}>•</span></span><span>Creative club for curious kids.</span></footer><style jsx>{`@media(max-width:700px){.shell{width:calc(100% - 32px)!important}.session-grid{grid-template-columns:1fr!important}.day-rail{margin-right:-16px;padding-right:16px}.filter-row{margin-right:-16px;padding-right:16px}}`}</style>
 </main>
}