"use client";

import { useEffect, useMemo, useState } from "react";

type Session = { id:string; topic:string; type:string; path:string|null; date:string|null; availableSeats:number|null; capacity:number|null; confirmedCount:number|null; runningClassIds:string[]; cover:string|null; avatar:string|null };
const filters=["All","Piano","Mỹ thuật","Little Piner"];
const parseDate=(d:string)=>new Date(d.length===10?`${d}T12:00:00`:d);
const dayKey=(d:string|null)=>d?parseDate(d).toISOString().slice(0,10):"unknown";
const dayLabel=(d:string)=>new Intl.DateTimeFormat("en-US",{weekday:"short"}).format(parseDate(d));
const dateLabel=(d:string)=>new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric"}).format(parseDate(d));
const timeLabel=(d:string|null)=>d&&d.length>10?new Date(d).toLocaleTimeString("vi-VN",{hour:"2-digit",minute:"2-digit"}):"Time TBA";
const normalize=(value:string|null)=>value?.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim()||"";
const matchesPath=(session:Session,filter:string)=>{if(filter==="All")return true;const value=normalize(`${session.path||""} ${session.topic||""}`);if(filter==="Piano")return value.includes("piano");if(filter==="Mỹ thuật")return value.includes("my thuat")||value.includes("art")||value.includes("architect");if(filter==="Little Piner")return value.includes("little piner")||value.includes("chibi")||value.includes("nguoi ban")||value.includes("piner");return false;};

export default function SessionsPage(){
 const [sessions,setSessions]=useState<Session[]>([]); const [filter,setFilter]=useState("All"); const [selectedDay,setSelectedDay]=useState(""); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
 const [selected,setSelected]=useState<Session|null>(null); const [name,setName]=useState(""); const [phone,setPhone]=useState(""); const [booking,setBooking]=useState(false); const [message,setMessage]=useState(""); const [success,setSuccess]=useState(false);
 useEffect(()=>{fetch("/api/os-sessions").then(async r=>{const data=await r.json();if(!r.ok)throw new Error(data.error||"Could not load sessions.");return data}).then(data=>{const list:Session[]=data.sessions||[];setSessions(list);const days:string[]=Array.from(new Set<string>(list.filter((s:Session)=>s.date).map((s:Session)=>dayKey(s.date))));setSelectedDay(days[0]||"")}).catch(e=>setError(e.message||"Could not load sessions.")).finally(()=>setLoading(false))},[]);
 const filtered=useMemo(()=>sessions.filter(s=>matchesPath(s,filter)),[filter,sessions]);
 const days:string[]=useMemo(()=>Array.from(new Set<string>(filtered.filter(s=>s.date).map((s:Session)=>dayKey(s.date)))).sort(),[filtered]);
 useEffect(()=>{if(!days.includes(selectedDay))setSelectedDay(days[0]||"")},[days,selectedDay]);
 const visible=filtered.filter(s=>dayKey(s.date)===selectedDay);
 const openBooking=(session:Session)=>{setSelected(session);setName("");setPhone("");setMessage("");setSuccess(false);};
 const closeBooking=()=>{if(!booking)setSelected(null)};
 const confirmBooking=async()=>{if(!selected||!name.trim()||!phone.trim())return;setBooking(true);setMessage("");const r=await fetch("/api/open-studio/book",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:name.trim(),phone:phone.trim(),sessionId:selected.id})});const data=await r.json();setBooking(false);if(!r.ok){setMessage(data.error||"Could not submit your booking request.");return}setSuccess(true);setMessage("Đã gửi yêu cầu ✓ PINO sẽ xác nhận với bạn qua Zalo.");};
 return <main style={{minHeight:"100vh",background:"#f4f0e7",color:"#171713"}}>
  <nav className="shell" style={{height:84,display:"flex",alignItems:"center",justifyContent:"space-between",borderBottom:"1px solid rgba(23,23,19,.16)"}}><a href="/" style={{fontWeight:700,fontSize:24,letterSpacing:"-.08em"}}>PINO<span style={{color:"#d65b42",marginLeft:3}}>•</span></a><a href="/open-studio" style={{fontSize:14,fontWeight:600}}>Open Studio →</a></nav>
  <section className="shell" style={{padding:"82px 0 42px"}}><p style={{fontSize:11,letterSpacing:".15em",fontWeight:700,color:"#69655d",marginBottom:18}}>PINO OPEN STUDIO</p><h1 style={{fontSize:"clamp(54px,7vw,96px)",lineHeight:.9,letterSpacing:"-.065em",maxWidth:850,margin:0}}>Find a session.<br/><em style={{fontFamily:"DM Serif Display,serif",fontWeight:400}}>Come make something.</em></h1><p style={{maxWidth:570,color:"#777269",fontSize:18,lineHeight:1.6,marginTop:28}}>Chọn một buổi bạn thích. Để lại tên và số Zalo — PINO sẽ xác nhận với bạn trước khi giữ chỗ.</p></section>
  <section className="shell" style={{paddingBottom:100}}>
   <div className="filter-row" style={{display:"flex",gap:8,overflowX:"auto",paddingBottom:4,marginBottom:26}}>{filters.map(item=><button key={item} onClick={()=>setFilter(item)} style={{whiteSpace:"nowrap",border:filter===item?"1px solid #171713":"1px solid rgba(23,23,19,.16)",background:filter===item?"#171713":"transparent",color:filter===item?"#fff":"#171713",borderRadius:999,padding:"10px 16px",cursor:"pointer",fontSize:13,fontWeight:600}}>{item}</button>)}</div>
   {!loading&&!error&&days.length>0&&<div className="day-rail" style={{display:"flex",gap:8,overflowX:"auto",borderBottom:"1px solid rgba(23,23,19,.16)",marginBottom:38}}>{days.map(d=>{const count=filtered.filter(s=>dayKey(s.date)===d).length;return <button key={d} onClick={()=>setSelectedDay(d)} style={{minWidth:92,padding:"14px 12px 17px",border:0,borderBottom:selectedDay===d?"3px solid #171713":"3px solid transparent",background:"transparent",cursor:"pointer",textAlign:"left"}}><div style={{fontSize:11,letterSpacing:".08em",fontWeight:700}}>{dayLabel(d).toUpperCase()}</div><div style={{fontSize:25,letterSpacing:"-.04em",marginTop:3}}>{dateLabel(d)}</div><div style={{fontSize:11,color:"#777269",marginTop:5}}>{count} {count===1?"session":"sessions"}</div></button>})}</div>}
   {loading&&<p style={{color:"#777269"}}>Loading sessions…</p>}{error&&<div style={{padding:24,border:"1px solid rgba(166,59,42,.35)",color:"#a63b2a"}}>{error}</div>}{!loading&&!error&&days.length===0&&<div style={{padding:50,borderTop:"1px solid rgba(23,23,19,.16)",color:"#777269"}}>No sessions are available yet. Check back soon.</div>}
   {!loading&&!error&&days.length>0&&visible.length===0&&<div style={{padding:"45px 0",color:"#777269"}}>Nothing is open this day. Try another day →</div>}
   <div className="session-grid" style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:14}}>{visible.map(session=>{const isPremium=session.type==="Premium";const seats=session.availableSeats;const soldOut=seats!==null&&seats<=0;return <article key={session.id} style={{background:"#e8e0d1",border:"1px solid rgba(23,23,19,.12)",overflow:"hidden"}}><div style={{aspectRatio:"16/9",background:session.cover?`url(${session.cover}) center/cover`:"linear-gradient(135deg,#d9d0bd,#c6d5ba)",position:"relative"}}>{session.avatar&&<img src={session.avatar} alt="" style={{position:"absolute",width:64,height:64,objectFit:"cover",borderRadius:"50%",left:20,bottom:20,border:"3px solid #f4f0e7"}}/>}<span style={{position:"absolute",top:18,right:18,background:isPremium?"#e2ebc0":"#f4f0e7",padding:"8px 10px",fontSize:10,letterSpacing:".1em",fontWeight:700}}>{isPremium?"PREMIUM":"OPEN STUDIO"}</span></div><div style={{padding:26}}><p style={{margin:"0 0 10px",fontSize:11,letterSpacing:".12em",fontWeight:700,color:"#777269"}}>{session.path||"PINO SESSION"}</p><h2 style={{fontSize:32,lineHeight:1,letterSpacing:"-.05em",margin:"0 0 10px"}}>{session.topic}</h2><div style={{borderTop:"1px solid rgba(23,23,19,.14)",paddingTop:16,display:"flex",justifyContent:"space-between",gap:15,fontSize:12}}><span>{timeLabel(session.date)}</span><span>{seats===null?"Seats TBA":soldOut?"Sold out":`${seats} seats left`}</span></div><button disabled={soldOut} onClick={()=>openBooking(session)} style={{width:"100%",marginTop:18,padding:"14px 18px",border:0,borderRadius:999,background:soldOut?"#c9c4b9":"#1d201a",color:"#fff",fontWeight:600,cursor:soldOut?"not-allowed":"pointer"}}>{soldOut?"Sold out":"Đăng ký tham gia →"}</button></div></article>})}</div>
  </section>
  {selected&&<div onClick={closeBooking} style={{position:"fixed",inset:0,background:"rgba(20,20,16,.48)",display:"grid",placeItems:"center",padding:20,zIndex:20}}><div onClick={e=>e.stopPropagation()} style={{width:"min(520px,100%)",background:"#f4f0e7",padding:30,border:"1px solid rgba(23,23,19,.16)",boxShadow:"0 25px 80px rgba(0,0,0,.18)"}}>{success?<><p style={{fontSize:11,letterSpacing:".12em",fontWeight:700,color:"#35633b"}}>REQUEST RECEIVED</p><h2 style={{fontSize:38,letterSpacing:"-.05em",margin:"8px 0 14px"}}>Hẹn gặp bạn tại PINO.</h2><p style={{fontSize:15,lineHeight:1.6,color:"#777269"}}>Yêu cầu của bạn cho <strong style={{color:"#171713"}}>{selected.topic}</strong> đã được gửi. PINO sẽ xác nhận chỗ với bạn qua Zalo.</p><button onClick={()=>setSelected(null)} style={{width:"100%",marginTop:22,padding:15,border:0,borderRadius:999,background:"#171713",color:"#fff",fontWeight:700}}>Done</button></>:<><p style={{fontSize:11,letterSpacing:".12em",fontWeight:700,color:"#777269"}}>ĐĂNG KÝ OPEN STUDIO</p><h2 style={{fontSize:38,letterSpacing:"-.05em",margin:"8px 0 8px"}}>{selected.topic}</h2><p style={{fontSize:13,lineHeight:1.5,color:"#777269",marginBottom:20}}>Chỉ cần tên và số Zalo. PINO sẽ xác nhận thủ công trước khi giữ chỗ.</p><label style={{display:"block",fontSize:12,fontWeight:700,marginBottom:7}}>Tên</label><input value={name} onChange={e=>setName(e.target.value)} placeholder="Tên của bạn" style={{width:"100%",boxSizing:"border-box",padding:14,border:"1px solid rgba(23,23,19,.2)",background:"transparent",marginBottom:14}}/><label style={{display:"block",fontSize:12,fontWeight:700,marginBottom:7}}>Số Zalo</label><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="09xx xxx xxx" inputMode="tel" style={{width:"100%",boxSizing:"border-box",padding:14,border:"1px solid rgba(23,23,19,.2)",background:"transparent"}}/><button disabled={booking||!name.trim()||!phone.trim()} onClick={confirmBooking} style={{width:"100%",marginTop:18,padding:15,border:0,borderRadius:999,background:booking||!name.trim()||!phone.trim()?"#c9c4b9":"#171713",color:"#fff",fontWeight:700}}>{booking?"Đang gửi…":"Gửi yêu cầu →"}</button>{message&&<p style={{marginTop:16,fontSize:13,color:message.includes("✓")?"#35633b":"#a63b2a"}}>{message}</p>}<button onClick={()=>setSelected(null)} disabled={booking} style={{marginTop:14,border:0,background:"transparent",textDecoration:"underline",cursor:"pointer"}}>Đóng</button></>}</div></div>}
  <footer className="shell" style={{borderTop:"1px solid rgba(23,23,19,.16)",padding:"28px 0 40px",display:"flex",justifyContent:"space-between",color:"#777269",fontSize:12}}><span>PINO<span style={{color:"#d65b42"}}>•</span></span><span>Creative club for curious kids.</span></footer><style jsx>{`@media(max-width:700px){.shell{width:calc(100% - 32px)!important}.session-grid{grid-template-columns:1fr!important}.day-rail{margin-right:-16px;padding-right:16px}.filter-row{margin-right:-16px;padding-right:16px}}`}</style>
 </main>
}
