export const PUBLIC_COPY_EN: Record<string, string> = {
  site_nav_why_pino: "Why PINO",
  site_nav_paths: "Four paths",
  site_nav_premium: "Premium Journey",
  site_nav_open_studio: "Explore Open Studio",
  site_primary_cta: "Explore Open Studio",
  site_footer_note: "A creative house for children.",
  site_footer_open_studio: "Open Studio",

  homepage_hero_eyebrow: "PINO HOUSE · CREATIVE HOME FOR KIDS",
  homepage_hero_title_lead: "A place for children to",
  homepage_hero_title_emphasis: "discover themselves.",
  homepage_hero_description: "Art and music become ways to observe, express and grow — at each child's own pace.",
  homepage_hero_cta: "Explore Open Studio",
  homepage_belief_eyebrow: "WHY PINO HOUSE",
  homepage_belief_title_lead: "More than learning a skill.",
  homepage_belief_title_emphasis: "Children are building a voice of their own.",
  homepage_belief_description: "PINO House gives children time to try, begin again, follow an idea and see themselves grow through what they create with their own hands.",
  homepage_model_eyebrow: "TWO WAYS TO GROW WITH PINO",
  homepage_model_title_lead: "Begin with exploration.",
  homepage_model_title_emphasis: "Go further with a journey.",
  homepage_model_description: "Families do not need to decide everything at the beginning. Children can explore first, then choose depth once they find what they want to pursue.",
  homepage_model_explore_title: "Open Studio",
  homepage_model_explore_description: "A gentle entry point to try something new, meet PINO and keep exploring without pressure.",
  homepage_model_premium_title: "Premium Journey",
  homepage_model_premium_description: "A structured long-term journey with mentors, deeper practice and visible evidence of growth.",
  homepage_paths_eyebrow: "FOUR PATHS",
  homepage_paths_title_lead: "A rhythm for every age.",
  homepage_paths_title_emphasis: "A direction for every child.",
  homepage_paths_description: "Four paths built around how children perceive and grow at each stage — through Art and Piano.",
  homepage_path_little_art_description: "Touch, look, shape and tell stories through color.",
  homepage_path_little_piano_description: "Discover rhythm, sound and the joy of making music.",
  homepage_path_art_description: "Develop visual language, technique and a point of view of their own.",
  homepage_path_piano_description: "Grow from listening and feeling into expression and confident performance.",
  homepage_open_studio_eyebrow: "OPEN STUDIO · EXPLORE",
  homepage_open_studio_title_lead: "Give your child an afternoon",
  homepage_open_studio_title_emphasis: "that truly matters.",
  homepage_open_studio_description: "No need to choose a path first. Children come to make, play, try something new and leave with a story of their own.",
  homepage_open_studio_cta: "Explore Open Studio",
  homepage_journey_eyebrow: "PREMIUM JOURNEY",
  homepage_journey_title_lead: "When a child wants to go deeper,",
  homepage_journey_title_emphasis: "PINO opens a journey.",
  homepage_journey_description: "Premium does not replace free exploration. It gives curiosity the time, structure and guidance to become lasting capability.",
  homepage_journey_progression_title: "A clear progression",
  homepage_journey_progression_description: "Experiences are sequenced so each one connects with and builds on what came before.",
  homepage_journey_mentor_title: "Mentors alongside",
  homepage_journey_mentor_description: "Children are observed, encouraged and supported at the right moments — never forced into one mold.",
  homepage_journey_artifacts_title: "Evidence of growth",
  homepage_journey_artifacts_description: "Artwork, performances and portfolios help families see the child's journey taking shape.",
  homepage_journey_ecosystem_title: "One ecosystem",
  homepage_journey_ecosystem_description: "Premium opens deeper learning, privileges and richer experiences across PINO.",
  homepage_space_eyebrow: "THE PINO HOUSE SPACE",
  homepage_space_title_lead: "A house where",
  homepage_space_title_emphasis: "ideas can grow.",
  homepage_space_description: "A space made for observing, touching, listening, trying and creating together. Warm like a home, open enough for every child to find a corner of their own.",
  homepage_reassurance_eyebrow: "FOR PARENTS",
  homepage_reassurance_title_lead: "Gentle enough to begin.",
  homepage_reassurance_title_emphasis: "Deep enough to grow.",
  homepage_reassurance_no_pressure_title: "No pressure to choose early",
  homepage_reassurance_no_pressure_description: "Children can explore before the family commits to a long-term journey.",
  homepage_reassurance_visible_title: "See what your child is building",
  homepage_reassurance_visible_description: "Work and experiences create concrete milestones — not just a score.",
  homepage_reassurance_guidance_title: "Know where your child is",
  homepage_reassurance_guidance_description: "Mentors share observations so families understand progress, interests and what could come next.",
  homepage_faq_eyebrow: "FREQUENTLY ASKED QUESTIONS",
  homepage_faq_title_lead: "Before your child",
  homepage_faq_title_emphasis: "starts exploring.",
  homepage_faq_trial_question: "Is Open Studio a trial class?",
  homepage_faq_trial_answer: "No. It is a standalone, gentle exploration experience with value of its own — not a sales trial.",
  homepage_faq_experience_question: "Does my child need to know art or piano first?",
  homepage_faq_experience_answer: "No. Open Studio is designed to begin with curiosity, experimentation and the child's own choices.",
  homepage_faq_model_question: "How are Explore and Premium Journey different?",
  homepage_faq_model_answer: "Explore lets children discover PINO freely through Open Studio. Premium combines exploration with a long-term path, mentors, progress and a body of work.",
  homepage_faq_age_question: "What ages is PINO House for?",
  homepage_faq_age_answer: "PINO currently has four paths for two age groups: Little Piner Art and Piano for ages 3–6; Art and Piano for children 7+.",
  homepage_final_eyebrow: "AN AFTERNOON AT PINO",
  homepage_final_title_lead: "Let your child begin",
  homepage_final_title_emphasis: "with curiosity.",
  homepage_final_description: "Choose an Open Studio that fits and let PINO prepare the rest.",
  homepage_final_cta: "Explore Open Studio",

  os_hero_eyebrow: "PINO HOUSE · OPEN STUDIO",
  os_hero_title_lead: "Give your child an afternoon",
  os_hero_title_emphasis: "with meaning.",
  os_hero_description: "A gentle space to touch art, music and discover what they genuinely want to explore.",
  os_hero_cta: "View Open Studio schedule",
  os_purpose_eyebrow: "01 · WHAT IS OPEN STUDIO?",
  os_purpose_title_lead: "An open doorway into",
  os_purpose_title_emphasis: "your child's world.",
  os_purpose_description: "Open Studio is a free exploration session where children can observe, try, make and talk with mentors inside PINO House.",
  os_purpose_explore_title: "Come to explore",
  os_purpose_explore_description: "No prior knowledge, no need to copy anyone. Children begin with their own curiosity.",
  os_purpose_listen_title: "Be truly listened to",
  os_purpose_listen_description: "Mentors notice how children respond, ask and create — rather than judging only the result.",
  os_purpose_artifact_title: "Leave with a trace",
  os_purpose_artifact_description: "An experience, a story or a small piece of work for the family to keep talking about together.",
  os_paths_eyebrow: "02 · WHO IS IT FOR?",
  os_paths_title_lead: "Four doorways,",
  os_paths_title_emphasis: "one house.",
  os_paths_description: "Choose by age and what your child wants to try. There is no need to decide a long-term path today.",
  os_model_eyebrow: "03 · EXPLORE & JOURNEY",
  os_model_title_lead: "Begin gently.",
  os_model_title_emphasis: "Go further when ready.",
  os_model_explore_description: "Drop in to explore new themes, materials and experiences — without commitment.",
  os_model_premium_description: "A structured learning journey for families who want their child to go deeper and grow sustainably.",
  os_schedule_eyebrow: "04 · UPCOMING SESSIONS",
  os_schedule_title_lead: "Choose a session",
  os_schedule_title_emphasis: "that fits your child.",
  os_schedule_description: "Each session is a real experience, with theme, age and remaining seats updated from the PINO schedule.",
  os_load_error: "The schedule is taking a short break.",
  os_load_error_description: "The rest of Open Studio is still here. Try again or contact PINO for the nearest available session.",
  os_retry: "Try again",
  os_no_sessions: "A new schedule is being prepared.",
  os_no_sessions_description: "There are no upcoming Open Studio sessions yet. Check back soon or message PINO to be notified when new sessions open.",
  os_registration_disabled: "Online registration is opening soon",
  os_registration_disabled_description: "Parents can browse the schedule today. PINO will open registration when the system is officially ready.",
  os_registration_detail_disabled_description: "Parents can still browse and choose a suitable experience. PINO will open registration once the system is officially ready.",
  os_session_detail_activity_heading: "What will my child do?",
  os_session_detail_skills_heading: "What will my child explore?",
  os_detail_register_cta: "Register for this session",
  os_registration_eyebrow: "REGISTRATION REQUEST",
  os_registration_title: "Family information",
  os_registration_description: "PINO will contact you to confirm the place. One registration is for one child.",
  os_registration_contact_label: "Parent / guardian name",
  os_registration_phone_label: "Phone number",
  os_registration_child_label: "Child's name",
  os_registration_birth_label: "Child's date of birth",
  os_next_eyebrow: "05 · AFTER CHOOSING A SESSION",
  os_next_title_lead: "Three simple steps,",
  os_next_title_emphasis: "without pressure.",
  os_final_eyebrow: "ONE AFTERNOON CAN OPEN A JOURNEY",
  os_final_title_lead: "Let your child begin with",
  os_final_title_emphasis: "curiosity.",
  os_final_description: "Open Studio is an invitation to explore. Premium Journey begins only when the child and family genuinely want to go deeper.",
  os_final_cta: "View Open Studio schedule",
};
