export const PIANOHOUSE_TRANSLATIONS: Record<string, string> = {
  "PINO House · Âm nhạc": "PINO House · Music",
  "Âm nhạc để biểu đạt. Tự tin theo năm tháng.": "Music for expression. Confidence over time.",
  "Tại PINO House, trẻ khám phá câu chuyện trong âm nhạc, học cách thể hiện mình qua phím đàn và từng bước tạo nên những khoảnh khắc đáng nhớ.": "At PINO House, children discover stories in music, learn to express themselves through the piano, and gradually create moments worth remembering.",
  "Khám phá PianoHouse": "Explore PianoHouse",
  "Học thử một buổi": "Try a session",

  "Bộ sưu tập": "Collections",
  "Con sẽ chơi gì?": "What will your child play?",
  "Những tuyển tập được chọn để mở trí tưởng tượng và đưa trẻ bước vào nhiều thế giới âm nhạc khác nhau.": "Curated collections that open the imagination and invite children into many different musical worlds.",
  "Xem các bộ sưu tập": "View collections",
  "Khám phá": "Explore",
  "Thế giới kỳ diệu": "Worlds of Wonder",
  "Những giai điệu vui tươi khơi mở tò mò và trí tưởng tượng.": "Playful melodies that spark curiosity and imagination.",
  "Chuyện kể điện ảnh": "Stories from Cinema",
  "Những chủ đề quen thuộc từ phim ảnh, được kể lại qua phím đàn.": "Familiar themes from film, retold through the piano.",
  "Chuyện kể bên phím đàn": "Stories at the Piano",
  "Những tác phẩm giàu hình ảnh, cảm xúc và câu chuyện riêng.": "Pieces rich in imagery, feeling, and stories of their own.",
  "Miền mộng tưởng": "Dreamscapes",
  "Âm nhạc dịu dàng cho những khoảnh khắc lắng lại và trí tưởng tượng bay xa.": "Gentle music for quiet moments and far-reaching imagination.",

  "Tiến trình": "Progression",
  "Hành trình lớn lên cùng âm nhạc": "Growing with music",
  "Một tiến trình rõ ràng để xây năng lực chơi đàn, khả năng biểu đạt và sự tự tin theo thời gian.": "A clear progression for building piano skills, expression, and confidence over time.",
  "Nốt nhạc đầu tiên": "First notes",
  "Làm quen bàn phím và tìm thấy niềm vui trong âm thanh.": "Meet the keyboard and discover joy in sound.",
  "Giai điệu": "Melody",
  "Chơi những câu nhạc đơn giản và bắt đầu phối hợp hai tay.": "Play simple phrases and begin coordinating both hands.",
  "Hai tay": "Two hands",
  "Xây khả năng phối hợp, kiểm soát và chơi liền mạch hơn.": "Build coordination, control, and smoother playing.",
  "Biểu cảm": "Expression",
  "Đưa âm nhạc thành câu chuyện bằng sắc thái, nhịp thở và cảm xúc.": "Turn music into a story through nuance, phrasing, and feeling.",
  "Trình diễn": "Performance",
  "Chia sẻ âm nhạc với sự tự tin, tự nhiên và niềm vui.": "Share music with confidence, ease, and joy.",

  "Câu chuyện học viên": "Student story",
  "Một bản nhạc. Hai anh em.": "One song. Two brothers.",
  "Hồng Thiện, 8 tuổi, đang ở trình độ Cấp 5. Với “Nơi này có anh”, Thiện phối hợp cùng anh trai Hồng Nhẫn để tạo nên một phần trình diễn rất riêng.": "Hồng Thiện, age 8, is currently at Level 5. In “Nơi này có anh,” Thiện performs together with his older brother Hồng Nhẫn to create a uniquely personal moment.",
  "8 tuổi": "Age 8",
  "Cấp 5": "Level 5",
  "Cùng anh trai": "With his brother",
  "Thiện trình diễn “Nơi này có anh” và phối hợp cùng anh trai Hồng Nhẫn — một khoảnh khắc để việc học đàn trở thành trải nghiệm âm nhạc được chia sẻ trong gia đình.": "Thiện performs “Nơi này có anh” with his older brother Hồng Nhẫn — a moment where learning piano becomes a musical experience shared within the family.",
  "Xem trên YouTube": "Watch on YouTube",

  "Trải nghiệm học": "Learning experience",
  "Một buổi học ở PianoHouse": "A lesson at PianoHouse",
  "Cấu trúc ấm áp, có nhịp điệu rõ ràng để nuôi dưỡng kỹ năng, sáng tạo và khả năng tự biểu đạt.": "A warm, clearly paced structure that nurtures skill, creativity, and self-expression.",
  "Tìm hiểu cách học": "See how learning works",
  "Chào & kết nối": "Hello & connect",
  "Lắng nghe, làm quen và cùng đặt nhịp cho buổi học.": "Listen, settle in, and find the rhythm for the session together.",
  "Kỹ thuật": "Technique",
  "Xây nền tảng vững, nhẹ nhàng và đẹp ngay từ đầu.": "Build a strong, relaxed, and beautiful foundation from the start.",
  "Tác phẩm": "Repertoire",
  "Học những bản nhạc vừa truyền cảm hứng, vừa tạo thử thách phù hợp.": "Learn pieces that inspire while offering the right level of challenge.",
  "Khám phá sắc thái, cách kể chuyện và cá tính âm nhạc riêng.": "Explore nuance, storytelling, and a musical voice of their own.",
  "Nhìn lại": "Reflect",
  "Nhận ra tiến bộ, ghi dấu thành quả và chọn mục tiêu tiếp theo.": "Notice progress, mark achievements, and choose what comes next.",

  "Dấu mốc": "Milestones",
  "Sân khấu & những khoảnh khắc đáng nhớ": "Stage & memorable moments",
  "Sân khấu thật, khán giả thật và những dấu mốc giúp trẻ nhìn thấy mình đang lớn lên.": "Real stages, real audiences, and milestones that help children see how they are growing.",
  "Xem hoạt động sắp tới": "See upcoming activities",
  "Buổi biểu diễn học viên": "Student performance",
  "Hướng dẫn chuyên sâu": "Focused guidance",
  "Trải nghiệm hòa nhạc": "Concert experience",
  "Chứng nhận & dấu mốc": "Certificates & milestones",
  "Khoảnh khắc PianoHouse": "PianoHouse moments",

  "Bắt đầu từ một buổi": "Start with one session",
  "Bắt đầu hành trình PianoHouse": "Begin the PianoHouse journey",
  "Học thử một buổi hoặc ghé Open Studio để tìm điểm bắt đầu phù hợp nhất cho con.": "Try one session or visit Open Studio to find the most natural starting point for your child.",
  "Khám phá Open Studio": "Explore Open Studio",

  "Học viên chơi đại dương cầm trong không gian PianoHouse": "A student playing grand piano in the PianoHouse space",
  "Không gian PianoHouse trong ánh sáng ấm": "PianoHouse in warm natural light"
};
